export const projects = [  
  {
    id: "instantes",
    title: "INSTANTES",
    category: ["fotografía"],
    description: "Una serie de fotografías analógicas que capturan la nostalgia del verano a través de mis ojos.",
    images: [
      "/images/projects/projectdetail/analogicas/analogicas.jpg",
      "/images/projects/projectdetail/analogicas/1.JPEG",
      "/images/projects/projectdetail/analogicas/2.JPEG",
      "/images/projects/projectdetail/analogicas/3.JPEG",
      "/images/projects/projectdetail/analogicas/4.JPEG",
      "/images/projects/projectdetail/analogicas/5.JPEG",
      "/images/projects/projectdetail/analogicas/8.JPEG",
    ],
    link: "/projects/instantes",
    client: "Proyecto personal",
    topic: "Fotografía",
    year: "Junio 2023-Agosto 2024",
  },
  {
    id: "nikita",
    title: "NIKITA!",
    category: ["ilustración"],
    description: "NIKITA! es un cómic de doble página que cuenta la historia de vida de Nika (mi perro), la mejor compañera que jamás pude haber tenido, quien me enseñó mucho sobre la capacidad de enfrentar las dificultades de la vida sin decir una palabra.",
    images: [
      "/images/projects/projectdetail/comic/comic.png",
      "/images/projects/projectdetail/comic/comicfinal.png",
      "/images/projects/projectdetail/comic/final.png",
      "/images/projects/projectdetail/comic/mockup.png",
      "/images/projects/projectdetail/comic/nika.jpg",
      "/images/projects/projectdetail/comic/paleta.jpg",
      "/images/projects/projectdetail/comic/personajejulia1.jpg",
      "/images/projects/projectdetail/comic/personajejulia2.jpg",
    ],
    link: "/projects/nikita",
    client: "Universidad",
    topic: "Ilustración",
    year: 2024
  },

  {
    id: "nohablemosdeltema",
    title: "NO HABLEMOS DEL TEMA",
    category: ["audiovisual", "fotografía"],
    description: "No hablemos del tema se desarrolla veinte años después de la misteriosa desaparición de los hombres, un evento que cambió completamente la humanidad. En este nuevo mundo, las mujeres han asumido el liderazgo, pero las cicatrices de una sociedad desigual persisten. A través de un reencuentro de amigas para celebrar el aniversario de la Gran Extinción, el cortometraje explora cómo, a pesar de la ausencia de hombres, las mujeres siguen lidiando con los restos de un sistema opresivo. Profundiza en la batalla interna para superar el pasado, las tensiones persistentes, y la pregunta de si realmente han avanzado o simplemente están sobreviviendo los ecos de un mundo que ya no existe.",
    images: [
      "/images/projects/projectdetail/corto/10.png", 
      "/images/projects/projectdetail/corto/7.png",
      "/images/projects/projectdetail/corto/3.png",
      "/images/projects/projectdetail/corto/4.png",
      "/images/projects/projectdetail/corto/5.png",
      "/images/projects/projectdetail/corto/2.JPEG",
      "/images/projects/projectdetail/corto/1.JPEG",
    ],
    link: "/projects/nohablemosdeltema",
    client: "Universidad",
    team: "Julia Camacho, Carmen Gascón, Celia Fernández, Mara Fernández, Alicia Navarrete",
    topic: "Cine, Dirección de Arte",
    year: 2024
  },
  
  {
    id: "unahabitacionpropia",
    title: "UNA HABITACIÓN PROPIA",
    category: ["editorial", "ilustración"],
    description: "Rediseño de la portada, contraportada, guardas e ilustración de la novela Una habitación propia de Virginia Woolf.",
    images: [    
      "/images/projects/projectdetail/unahabitacionpropia/ilustración.png",
      "/images/projects/projectdetail/unahabitacionpropia/entero.png",
      "/images/projects/projectdetail/unahabitacionpropia/2.png",
      "/images/projects/projectdetail/unahabitacionpropia/3.png",
      "/images/projects/projectdetail/unahabitacionpropia/4.png",
      "/images/projects/projectdetail/unahabitacionpropia/6.png",
      "/images/projects/projectdetail/unahabitacionpropia/5.png",
      "/images/projects/projectdetail/unahabitacionpropia/7.png",

    ],
    link: "/projects/unahabitacionpropia",
    client: "Universidad",
    topic: "Diseño Editorial, Ilustración",
    year: "octubre 2025",
  },
  
  {
    id: "36daysoftype",
    title: "#36DAYSOFTYPE",
    category: ["ilustración"],
    description: "Una serie de 3 letras para el proyecto tipográfico #36daysoftype. Acuarela, lápices de color y post-edición en Photoshop.",
    images: [
      "/images/projects/projectdetail/letritas/a.png",
      "/images/projects/projectdetail/letritas/a.png",
      "/images/projects/projectdetail/letritas/i.png",
      "/images/projects/projectdetail/letritas/v.png",
    ],
    link: "/projects/36daysoftype",
    client: "Universidad",
    topic: "Diseño Gráfico, Ilustración",
    year: "2024",
  },
  
  {
    id: "PAM!25",
    title: "PAM!25",
    category: ["identidad visual", "gráfico"],
    description: "Propuesta de identidad gráfica de PAM! 2025. Muestra de Producciones Artísticas y Multimedia Facultat de Belles Arts (UPV).",
    images: [
      "/images/projects/projectdetail/PAM/FONDO.png",
      "/images/projects/projectdetail/PAM/2.png",
      "/images/projects/projectdetail/PAM/3.png",
      "/images/projects/projectdetail/PAM/6.png",
      "/images/projects/projectdetail/PAM/7.png",
      "/images/projects/projectdetail/PAM/8.png",
      "/images/projects/projectdetail/PAM/9.png",
      "/images/projects/projectdetail/PAM/12.png",
      "/images/projects/projectdetail/PAM/FOLLETO.png",
      "/images/projects/projectdetail/PAM/totebag.jpg",
    ],
    link: "/projects/PAM!25",
    client: "Universidad",
    team: "Julia Camacho, Carmen Gascón, Celia Fernández, Marina López",
    topic: "Diseño Gráfico",
    year: "Marzo 2025"
  },
   {
    id: "grain",
    title: "GRAIN",
    category: ["editorial", "fotografía"],
    description: "Proyecto de diseño editorial y fotográfico completo de la revista GRAIN, dedicada a la fotografía analógica.",
     images: [
            "/images/projects/projectdetail/grain/1.png",
            "/images/projects/projectdetail/grain/2.png",
            "/images/projects/projectdetail/grain/1.2.png",
            "/images/projects/projectdetail/grain/2.1.png",
            "/images/projects/projectdetail/grain/2.2.png",
            "/images/projects/projectdetail/grain/2.3.png",
            "/images/projects/projectdetail/grain/2.4.png",
            "/images/projects/projectdetail/grain/2.5.png",
            "/images/projects/projectdetail/grain/2.6.png",
            "/images/projects/projectdetail/grain/3.png",
            "/images/projects/projectdetail/grain/4.png",
            "/images/projects/projectdetail/grain/5.png",
            "/images/projects/projectdetail/grain/6.png",
            "/images/projects/projectdetail/grain/6.1.png",  
            "/images/projects/projectdetail/grain/7.png",
            "/images/projects/projectdetail/grain/7.2.png",
            "/images/projects/projectdetail/grain/8.png",
            "/images/projects/projectdetail/grain/9.png",
            "/images/projects/projectdetail/grain/10.png",
    ],
    link: "/projects/grain",
    client: "Universidad",
    team: "Julia Camacho",
    topic: "Diseño Editorial, Fotografía",
    year: "Enero 2026"
  },

  
  {
    id: "donesdeciencia",
    title: "DONES DE CIÈNCIA",
    category: ["identidad visual"],
    description: "Propuesta de rebranding de la iniciativa Dones de Ciència para la Universitat Politècnica de València. El diseño tangible consta de una figura creada con arcilla polimérica y placas de Petri hechas de resina, pigmentos de color y joyería.",
    images: [
      "/images/projects/projectdetail/donesdeciencia/capsula1.png",
      "/images/projects/projectdetail/donesdeciencia/presentación-10.jpg",
      "/images/projects/projectdetail/donesdeciencia/capsulas.gif",
      "/images/projects/projectdetail/donesdeciencia/logos.jpg",
      "/images/projects/projectdetail/donesdeciencia/tipografia.jpg",
      "/images/projects/projectdetail/donesdeciencia/logo(sintexto).gif", 
      "/images/projects/projectdetail/donesdeciencia/carteles.jpg",      
      "/images/projects/projectdetail/donesdeciencia/mockups.jpg",
      "/images/projects/projectdetail/donesdeciencia/mockup2.jpg",
    ],
    link: "/projects/donesdeciencia",
    client: "Universidad",
    team: "Julia Camacho, Celia Fernández, Marina López",
    topic: "Diseño Gráfico",
    year: "Junio 2024"
  },
  {
    id: "PAW",
    title: "LOS IRRESISTIBLES",
    category: ["identidad visual", "gráfico"],
    description: "Identidad visual de PAWSSIBLE y desarrollo de LOS IRRESISTIBLES: campaña de sensibilización sobre la adopción y manutención de animales seniors y con necesidades especiales ",
    images: [
      "/images/projects/projectdetail/PAW/1.png",
      "/images/projects/projectdetail/PAW/2.png",
      "/images/projects/projectdetail/PAW/3.png",
      "/images/projects/projectdetail/PAW/4.png",
      "/images/projects/projectdetail/PAW/5.png",
      
      "/images/projects/projectdetail/PAW/7.png",
      "/images/projects/projectdetail/PAW/8.png",
      "/images/projects/projectdetail/PAW/9.png",
      "/images/projects/projectdetail/PAW/10.png",
    ],
    link: "/projects/PAW",
    client: "Universidad",
    team: "Julia Camacho",
    topic: "Diseño Gráfico, Identidad Visual",
    year: "Noviembre 2025"
  },
   {
    id: "futura",
    title: "FUTURA",
    category: ["gráfico"],
    description: "Proyecto de diseño del cartel de la tipografía FUTURA. Incluye información sobre el autor y características propias de la tipografía.",
    images: [
      "/images/projects/projectdetail/futura/1.png",
      "/images/projects/projectdetail/futura/2.png",
     
    ],
    link: "/projects/futura",
    client: "Universidad",
    team: "Julia Camacho, Carmen Gascón",
    topic: "Diseño Gráfico",
    year: "Septiembre 2025"
  },
  
  {
    id: "cxmbia",
    title: "CXMBIA",
    category: ["identidad visual", "audiovisual"],
    description: "Campaña para concienciar sobre la gravedad de la moda rápida. Bajo el lema Cambia tus hábitos, no tu estilo, queremos reflejar el rechazo al consumismo sin dejar de lado la moda y su evolución, fomentando el reciclaje de prendas existentes para darles nueva vida, mientras estimulamos tu propia creatividad y te damos la oportunidad de explorar tu estilo personal.",
    images: [
      "/images/projects/projectdetail/cambia/2.png",   
      "/images/projects/projectdetail/cambia/7.png", 
      "/images/projects/projectdetail/cambia/8.PNG",
      "/images/projects/projectdetail/cambia/9.png",
      "/images/projects/projectdetail/cambia/21.png",
      "/images/projects/projectdetail/cambia/33.png",
    ],
    link: "/projects/cxmbia",
    client: "Universidad",
    team: "Julia Camacho, Carmen Gascón, Celia Fernández, Mara Fernández, Alicia Navarrete",
    topic: "Diseño Gráfico, Multimedia",
    year: "Enero 2025"
  },
  
  {
    id: "esperanza",
    title: "ESPERANZA",
    category: ["gráfico"],
    description: "Proyecto de diseño del cartel que promociona la obra de teatro EMOCIONAL de la dramaturga Maja Zade. La obra explora los diferentes tipos de emociones que experimentamos como seres humanos desde una perspectiva disruptiva y contemporánea. En nuestro caso, tuvimos que representar la esperanza.",
    images: [
      "/images/projects/projectdetail/esperanza/2.jpg",
      "/images/projects/projectdetail/esperanza/esperanza.jpg",
      "/images/projects/projectdetail/esperanza/4.jpg",
      "/images/projects/projectdetail/esperanza/mockup.jpg",
    ],
    link: "/projects/esperanza",
    client: "Universidad",
    team: "Julia Camacho, Carmen Gascón",
    topic: "Diseño Gráfico",
    year: "Enero 2025"
  },
  {
    id: "clasicosdelcine",
    title: "CLASICOS DEL CINE",
    category: ["identidad visual", "ilustración"],
    description: "Identidad visual y packaging para el snack de palomitas del Ciclo de Cine Clásico de la Facultad de Bellas Artes de la UCM.  La marca conecta con el  alumnado  de Bellas Artes mediante personajes , basados en  memes, que reinterpretan la solemnidad del cine clásico con un tono cercano y divertido. ",
    images: [
      "/images/projects/projectdetail/clasicosdelcine/portada.png",
      "/images/projects/projectdetail/clasicosdelcine/1.png",      
      "/images/projects/projectdetail/clasicosdelcine/2.png", 
      "/images/projects/projectdetail/clasicosdelcine/3.png",
      "/images/projects/projectdetail/clasicosdelcine/4.png",
      "/images/projects/projectdetail/clasicosdelcine/5.png", 
    ],
    link: "/projects/clasicosdelcine",
    client: "Universidad",
    team: "Julia Camacho",
    topic: "Diseño Gráfico, Identidad Visual",
    year: "Diciembre 2025"
  },
   

  
];